export default {
  components: [
    {
      name: "button",
      variants: ["primary", "secondary", "tertiary", "ghost", "link"],
      states: ["hover", "focus", "active", "disabled"],
      size: ["small", "medium", "large"],
      icon: ["left", "right"],
      iconPosition: ["left", "right"],
      iconSize: ["small", "medium", "large"],
      iconColor: ["primary", "secondary", "tertiary"],
    },
    {
      name: "input",
      variants: ["primary", "secondary", "tertiary"],
      states: ["hover", "focus", "active", "disabled"],
      size: ["small", "medium", "large"],
      iconPosition: ["left", "right"],
      type: ["text", "email", "password", "number", "tel", "url"],
    },
    {
      name: "select",
      variants: ["primary", "secondary", "tertiary"],
      states: ["hover", "focus", "active", "disabled"],
      size: ["small", "medium", "large"],
      iconPosition: ["left", "right"],
    },
    {
      name: "selectItem",
    },
    "textarea",
    "checkbox",
    "radio",
    "switch",
    "slider",
    "progress",
    "spinner",
    "avatar",
    "badge",
    "card",
    "chip",
    "dialog",
    "divider",
    "list",
    "menu",
    "navigation",
    "pagination",
    "panel",
    "popover",
    "table",
    "tabs",
    "tooltip",
    "typography",
    "grid",
    "layout",
    "media",
    "overlay",
    "scroll",
    "space",
    "utilities",
  ],
  theme: {
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    typography: {
      font: "",
      size: "",
      weight: "",
    },
    spacing: {
      padding: "",
      margin: "",
    },
    border: {
      radius: "",
      width: "",
    },
    shadow: {
      offset: "",
      blur: "",
      color: "",
    },
  },
  syntax: {
    spaces: "",
    indent: "",
    quotes: "",
    semicolons: "",
    lineBreaks: "",
  }
}